Updated file browser with proper function and variable indentation
wiremod/advdupe2 pull request #311
Opened 2020-10-10 11:25 UTC by dvdvideo1234

2020-10-10 11:29 UTC, dvdvideo1234 commented on lua/advdupe2/file_browser.lua
> +		local asvNode = AdvDupe2.FileBrowser.AutoSaveNode
Use these two instead of indexing multiple times

2020-10-10 11:29 UTC, dvdvideo1234 commented on lua/advdupe2/file_browser.lua
> +	local fbrSearch = vgui.Create("advdupe2_browser_panel", AdvDupe2.FileBrowser)
Create reference so that it point to `advdupe2_browser_panel` and populate `AdvDupe2.FileBrowser.Search` with it

2020-10-10 11:31 UTC, dvdvideo1234 commented
Make it use [non-gmod dedicated](https://github.com/wiremod/advdupe2/pull/311/commits/8d19f6be69e9664be2483e1dba8a1d239c7c87fa?w=1) comments `and` and `or`

2020-10-28 20:25 UTC, thegrb93 commented
Will start advdupe2 work soon. Finishing up starfall this week.

2020-10-28 20:31 UTC, thegrb93 requested changes

2020-10-28 20:31 UTC, thegrb93 commented on lua/advdupe2/file_browser.lua
> +  -- CollapseChildren(node) return end
This should be deleted

2020-10-28 20:32 UTC, thegrb93 commented
I finished reviewing and that looks like the only change needed. Can merge after that is fixed.

2020-11-01 18:27 UTC, dvdvideo1234 commented on lua/advdupe2/file_browser.lua
> +  -- CollapseChildren(node) return end
Done in https://github.com/wiremod/advdupe2/pull/311/commits/6162228bd09e512d8d319abb1230e1f01a14dcd0

2020-11-01 20:11 UTC, merged