Debug version of sv_clipboard.lua
wiremod/advdupe2 pull request #316
Opened 2020-10-15 15:40 UTC by dvdvideo1234

2020-10-16 13:50 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +			-- Avoid making a vector just to compare it
Use the setup compare lookup

2020-10-16 13:50 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +		if(Constraint.Type == "Slider" and Key == "material") then
Patch the sliders and default the rope material to `cable/cable`

2020-10-16 13:50 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +			local OK, ERR = pcall(ModFunction, Player, Ent, Data)
Use local return values here

2020-10-16 13:50 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +		local OK, ERR = pcall(duplicator.EntityModifiers["mass"], Player, Ent, Ent.EntityMods["mass"])
Here too

2020-10-16 13:50 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +			for k, v in pairs(Queue.CreatedEntities) do
Utilize the value of `k` instead of `_`

2020-10-16 13:54 UTC, dvdvideo1234 commented
@thegrb93 The file is ready for code review, thanks !

2020-10-16 17:43 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +	local OK, Ent = pcall(Factory.Func, unpack(Args))
Rename to `OK`

2020-10-16 17:43 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +			-- Translate keys from old system
Use the table lookup instead of comparing bunch of strings

2020-10-16 17:43 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +	hook.Call("AdvDupe_FinishPasting", nil, {
This looks a bit nicer

2020-10-16 17:43 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +			hook.Call("AdvDupe_FinishPasting", nil, {
Make another hook pretty

2020-10-16 18:44 UTC, thegrb93 commented
This is almost too much to review. Please no more

2020-10-22 06:14 UTC, dvdvideo1234 commented
@thegrb93 Code style is not changed. The no-whitespace diff is [located here](https://github.com/wiremod/advdupe2/pull/316/files?w=1).

2020-10-22 06:37 UTC, thegrb93 commented
I know. It's still too much. I'll do when I get time.

2020-10-28 23:19 UTC, thegrb93 requested changes

2020-10-28 23:19 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +	local ConBuDupeInfo = Constraint.BuildDupeInfo
Rename this local `buildInfo`

2020-10-28 23:19 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +	local OK, Ent = pcall(Factory.Func, unpack(Args))
`ok` instead pls

2020-10-28 23:19 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +			local OK, ERR = pcall(ModFunction, Player, Ent, Data)
`err` instead of `ERR`

2020-10-28 23:20 UTC, thegrb93 commented
Mixing logic changes with hundreds of whitespace changes is extremely frowned upon. Don't do it again or I'll just close the PR.

The whitespace changes look fine except for the requested changes. The logic changes will need testing to make sure they work fine.

2020-10-30 13:44 UTC, dvdvideo1234 commented
Ok, I will turn off automatic lode alignment when do logic changes. Thanks!

2020-10-30 13:52 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +				if Key == "Bone" .. i or Key == "Bone" then
Doubt it.. What concerns me are those concatenations.. When you have `Bone13` or `Bonemanipulator1` they both start with `Bone`, but must handled differently. Same for `WPos%d` Maybe a pattern can be used to mach these. What's your `lookup_table.Pattern.bone = "Bone%d"` and later in the key `Key:find(lookup_table.Pattern.bone) or lookup_table.BONE[Key]`

2020-10-30 14:00 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +			local OK, ERR = pcall(ModFunction, Player, Ent, Data)
Done in all places

2020-10-30 14:01 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +	local ConBuDupeInfo = Constraint.BuildDupeInfo
Done.

2020-10-30 14:04 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +				if Key == "Bone" .. i or Key == "Bone" then
I don't know however the concatenation or pattern matching is faster though.

2020-10-30 14:09 UTC, dvdvideo1234 commented
For `if(Constraint.Type == "Slider" and Key == "material") then` the `else` statement was used by default when you create a entity/constraint and a value is not present, the script fill it with false. So I decided to keep it and change only the sliders with a missing texture ( The value `false` is being defaulted by Garry to `cable/cable` and it and the slider creation function accepts string ). It is true, however when we make it throw error, it will show `the hidden rocks` when duping, so we can identify what is not being dupped with correct parameters in the first place. I think the original author went for the lazy approach putting `false` ;)

2020-10-30 18:07 UTC, thegrb93 requested changes

2020-10-30 18:07 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
>  				second:SetAngles(ConBuDupeInfo.Ent2Ang)
Looks like you missed some `ConBuDupeInfo`

2020-10-30 18:12 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +				if Key == "Bone" .. i or Key == "Bone" then
Yeah nevermind. I'll refactor this function perhaps later.

2020-10-30 18:16 UTC, thegrb93 requested changes

2020-10-30 18:16 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +		if(Constraint.Type == "Slider" and Key == "material") then
Can you delete this? It doesn't belong. https://github.com/wiremod/advdupe2/issues/319 will investigate replacing the 'false's to 'nil's.

2020-10-31 14:37 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +		Val = Val or false
Reverted the old way the value is calculated

2020-10-31 14:37 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +	},
Added: Hash lookup to remove concatenations

2020-10-31 17:50 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> -			if (Key == "VehicleTable" and EntTable[Key] and EntTable[Key].KeyValues) then
Table lookups aren't faster than single string comparisons. Pls revert.

2020-10-31 17:51 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +		["VehicleTable"] = true
This key is wrong

2020-10-31 17:52 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +				if Key:find(gtSetupTable.FRM.E) then
Revert this please. This breaks the logic.

2020-10-31 17:53 UTC, thegrb93 commented
I'm getting tired of reviewing this. Stop adding changes.

2020-10-31 17:55 UTC, thegrb93 commented
Also your force-push means I have to look over the whole thing again.

2020-11-01 09:11 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +				if Key:find(gtSetupTable.FRM.E) then
Done.

2020-11-01 09:12 UTC, dvdvideo1234 commented on lua/advdupe2/sv_clipboard.lua
> +		["VehicleTable"] = true
Fixed.

2020-11-02 22:05 UTC, thegrb93 commented
Just needs testing now.

2020-11-26 01:17 UTC, merged

2020-11-26 10:05 UTC, dvdvideo1234 commented
@thegrb93 Cheers !