Fixes #364
wiremod/advdupe2 pull request #373
Opened 2021-07-10 18:40 UTC by dvdvideo1234

2021-07-12 19:02 UTC, thegrb93 commented
The problem is actually due to a corrupted dupe file. We simply need more sanity checking in https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sh_codec.lua#L423

2021-07-12 19:34 UTC, thegrb93 commented
PhysicsObjects should never be nil actually. I don't know if this fixes that. Would help if it wasn't polluted with whitespace changes.

2021-07-12 19:54 UTC, thegrb93 commented
In this case, we just need a loop to make sure all dupe.Entities have a PhysicsObjects table.

2021-07-12 20:49 UTC, thegrb93 commented
The problem is a corrupt dupe. Just need more sanity checking in https://github.com/wiremod/advdupe2/blob/master/lua/advdupe2/sh_codec.lua#L423 . In this case, we just need a loop to make sure all dupe.Entities have a PhysicsObjects table.

2021-07-13 17:14 UTC, thegrb93 commented
I'll try to review later but stop adding stuff

2021-07-13 20:32 UTC, dvdvideo1234 reviewed
I wonder is it worth it to use  `["..key.."]["..data.Class.."]["..data.Model.."]"`  instead of `["..tostring(key).."]["..tostring(data.Class).."]["..tostring(data.Model).."]"` ?

2021-07-13 20:32 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	for key, data in pairs(dupe.Entities) do
This loops trough all the entities and checks for `PhusObj[0]`

2021-07-13 20:32 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +		while buff:ReadByte() ~= 0 do
I really do prefer the standard Lua operators

2021-07-13 20:32 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> -	GhostEntity.Phys = EntTable.PhysicsObjects and EntTable.PhysicsObjects[0] or nil
Revert the old war of extracting this

2021-07-13 20:32 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> -		if not dupe.Entities[dupe.HeadEnt.Index].PhysicsObjects[0].LocalPos then return false, "Missing PhysicsObject[0].LocalPos from HeadEnt Entity table" end
For improved readability put the return in a new line so the code can be visible in only one screen

2021-07-13 20:32 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	local head = dupe.HeadEnt.Index -- Localize head ID for faster indexing
Localize the head index and use it down the code

2021-07-13 20:32 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	if not dupe.Entities then return false, "Missing Entities table" end
Check for Heard info and entities first

2021-07-13 22:58 UTC, thegrb93 requested changes

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +		for k, v in pairs(dupe.Entities)do
Add space before 'do'

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +				Pos = v.LocalPos * 1
Do same thing here as what you did on line 27 and remove the *1

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +		for k, v in pairs(dupe.Entities)do
Add space before 'do'

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	if(not EntTable.Model or EntTable.Model == "" or
Change to
```lua
if not EntTable.Model or EntTable.Model:sub(-4,-1) ~= ".mdl" then
    EntTable.Model = "models/error.mdl"
end
```

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	local varGhosts = GetConVar("advdupe2_limit_ghost")
Undo this. GetConVarNumber is faster

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	AdvDupe2.CurrentGhost, AdvDupe2.GhostEntities = 1, {}
Undo this

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	if(GetConVar("advdupe2_original_origin"):GetBool())then
Please revert all the GetConVar changes

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +	local ret, m = true, 0
Undo this. It's ok in some places but you're making it harder to read here

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +			if(enc[TypeID(k)] ~= noserializer and
Please make this 1 line again

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +local reference, read4, read5 = 0
Change to
```lua
local reference = 0
local read4, read5
```

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +		local t, k = {}
Undo this

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +	for i = 1, 246 do
Undo back to 1 line

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +	for i = 1, 245 do
Undo back to 1 line

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	local count, time, desc, date, creator = 0
Change to
```lua
local count = 0
local time, desc, date, creator
```

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +		local z, Pos, Ang = dupe.HeadEnt.Z
Change to
```lua
local z = dupe.HeadEnt.Z
local Pos, Ang
```

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +			if(ghost and ghost.Phys) then
This if check is unnessesary. Also please undo the LocalToWorld change

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +		local t, k, v = {}, 0
```lua
local t = {}
local k = 0
local v
```

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +		if not data.PhysicsObjects[0] then
I'm not sure all entities will have a 0 index in PhysicsObjects. I think maybe only the headent does? Will need to test.

2021-07-13 22:58 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +			return false, "Missing PhysicsObject[0].Angle from HeadEnt Entity table" end
These should all get checked in the loop I think.

2021-07-14 07:12 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +				Pos = v.LocalPos * 1
It just creates a vector so I'll cal the copy-constructor

2021-07-14 07:17 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +	local varGhosts = GetConVar("advdupe2_limit_ghost")
It is [deprecated](https://wiki.facepunch.com/gmod/Global.GetConVarNumber). I will localize the convar objects instead

2021-07-14 07:25 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +		if not data.PhysicsObjects[0] then
Oke

2021-07-14 07:38 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +		local t, k, v = {}, 0
Done

2021-07-14 07:38 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +			if(ghost and ghost.Phys) then
done

2021-07-14 07:39 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +		local z, Pos, Ang = dupe.HeadEnt.Z
done

2021-07-14 07:40 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +	local varGhosts = GetConVar("advdupe2_limit_ghost")
```
local varGhosts = GetConVar("advdupe2_limit_ghost")
local varOrgOrg = GetConVar("advdupe2_original_origin")
local varOWorld = GetConVar("advdupe2_offset_world")
local varOffseZ = GetConVar("advdupe2_offset_z")
local varOPitch = GetConVar("advdupe2_offset_pitch")
local varOYaw   = GetConVar("advdupe2_offset_yaw"  )
local varORoll  = GetConVar("advdupe2_offset_roll" )
```

2021-07-14 07:40 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +	if(not EntTable.Model or EntTable.Model == "" or
done

2021-07-14 07:41 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +		for k, v in pairs(dupe.Entities)do
done in all places for `)do` and `)then`

2021-07-14 07:52 UTC, dvdvideo1234 commented
@thegrb93 

I've exported the `dupe` table internal stricture: [dupe.txt](https://github.com/wiremod/advdupe2/files/6814426/dupe.txt)

2021-07-14 22:16 UTC, thegrb93 commented
>dvdvideo1234 force-pushed the dvdvideo1234:patch-1 branch 3 times, most recently from ebfa2be to f655d3a 15 hours ago

Did you know that if you force-push, I have to review the whole thing again?

2021-07-15 06:17 UTC, dvdvideo1234 commented
It is only https://github.com/wiremod/advdupe2/pull/373/commits/f655d3ad9173582a99669ffafce92cb0f23a575e though

2021-07-19 18:23 UTC, thegrb93 commented
@dvdvideo1234 make sure you expand the hidden conversations, you haven't completed them. There were so many that it collapsed.

2021-07-20 05:44 UTC, dvdvideo1234 commented
@thegrb93 

I already completed these. You can expand them if you like. In every one I've wrote something. ;)

2021-07-20 05:47 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +		for k, v in pairs(dupe.Entities)do
This is already done. For `do` and  `then`

2021-07-20 05:55 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +			if(enc[TypeID(k)] ~= noserializer and
Already done in https://github.com/wiremod/advdupe2/pull/373/files#diff-7d82d18e4d04dc1e62ad7990c0f8fd4df8031a304d885ee0717b28046a195ce3R106

2021-07-20 05:56 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	local ret, m = true, 0
To be done in the next commit

2021-07-20 05:58 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +	AdvDupe2.CurrentGhost, AdvDupe2.GhostEntities = 1, {}
To be done in the next commit.

2021-07-20 05:59 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +local reference, read4, read5 = 0
To be done in the next commit

2021-07-20 05:59 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +		local t, k = {}
Next commit

2021-07-20 06:00 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	for i = 1, 245 do
Next commit

2021-07-20 06:01 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +	local count, time, desc, date, creator = 0
Done in https://github.com/wiremod/advdupe2/pull/373/files#diff-9fc63e66fcc4cc91d382610d0ffc4e01c5d4eb5fa9ceea839828a543efd6d714R14

2021-07-20 06:02 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	for i = 1, 246 do
Next commit

2021-07-20 06:07 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +	AdvDupe2.CurrentGhost, AdvDupe2.GhostEntities = 1, {}
Done in https://github.com/wiremod/advdupe2/pull/373/commits/c081205a3065e9c4e05ca6a067995b832961b67c

2021-07-20 06:07 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	local ret, m = true, 0
Done in https://github.com/wiremod/advdupe2/pull/373/commits/c081205a3065e9c4e05ca6a067995b832961b67c

2021-07-20 06:07 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +local reference, read4, read5 = 0
Done in https://github.com/wiremod/advdupe2/pull/373/commits/c081205a3065e9c4e05ca6a067995b832961b67c

2021-07-20 06:07 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +		local t, k = {}
Done in https://github.com/wiremod/advdupe2/pull/373/commits/c081205a3065e9c4e05ca6a067995b832961b67c

2021-07-20 06:08 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	for i = 1, 246 do
Done in https://github.com/wiremod/advdupe2/pull/373/commits/c081205a3065e9c4e05ca6a067995b832961b67c

2021-07-20 06:08 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	for i = 1, 245 do
Done in https://github.com/wiremod/advdupe2/pull/373/commits/c081205a3065e9c4e05ca6a067995b832961b67c

2021-07-20 06:10 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +		for k, v in pairs(dupe.Entities)do
Done in https://github.com/wiremod/advdupe2/pull/373/commits/f655d3ad9173582a99669ffafce92cb0f23a575e

2021-07-20 06:14 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +		for k, v in pairs(dupe.Entities)do
Done in https://github.com/wiremod/advdupe2/pull/373/commits/f655d3ad9173582a99669ffafce92cb0f23a575e

2021-07-20 06:21 UTC, dvdvideo1234 commented
@thegrb93

Hmm, it says there is still one left, but I doubt this is really the case. All appear to be resolved already. Very weird.

2021-07-20 06:27 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +			return false, "Missing PhysicsObject[0].Angle from HeadEnt Entity table" end
Done in https://github.com/wiremod/advdupe2/pull/373/files#diff-7d82d18e4d04dc1e62ad7990c0f8fd4df8031a304d885ee0717b28046a195ce3R436

2021-07-20 06:34 UTC, dvdvideo1234 reviewed
I noticed that the conversation have been resolved in the `Conversation` tab, but they were still unresolved in the `Files changed` tab. Very, very weird ... Still unresolved.

2021-07-20 06:34 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +		local t, k = {}
Done in https://github.com/wiremod/advdupe2/pull/373/commits/c081205a3065e9c4e05ca6a067995b832961b67c

2021-07-20 06:34 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	for i = 1, 246 do
Done in https://github.com/wiremod/advdupe2/pull/373/commits/c081205a3065e9c4e05ca6a067995b832961b67c

2021-07-20 06:34 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +	for i = 1, 245 do
Done in https://github.com/wiremod/advdupe2/pull/373/commits/c081205a3065e9c4e05ca6a067995b832961b67c

2021-07-20 23:02 UTC, thegrb93 requested changes

2021-07-20 23:02 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	local cache = {}
Move this back where it was

2021-07-20 23:02 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +		return false, "Missing HeadEnt index ["..dupe.HeadEnt.Index.."] from Entities table" end
One line please

2021-07-20 23:02 UTC, thegrb93 commented on lua/advdupe2/sh_codec.lua
> +				..key.."]["..data.Class.."]["..data.Model.."]" end
Make these one line

2021-07-21 13:49 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +		local t = {}
Done

2021-07-21 13:50 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +				p.Pos        = Vector(Pos or p.LocalPos)
Done

2021-07-21 13:52 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +	local cache = {}
Done

2021-07-21 13:53 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +		return false, "Missing HeadEnt index ["..dupe.HeadEnt.Index.."] from Entities table" end
Done

2021-07-21 13:54 UTC, dvdvideo1234 commented on lua/advdupe2/sh_codec.lua
> +				..key.."]["..data.Class.."]["..data.Model.."]" end
Done

2021-07-22 19:41 UTC, thegrb93 requested changes

2021-07-22 19:41 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	local origin, offsetang = Vector(), Angle()
origin and offsetang can be nil. The code before was fine

2021-07-22 19:50 UTC, thegrb93 requested changes

2021-07-22 19:50 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	local origin, oangle, headpos, headang
Maybe change 'origin' and 'oangle' to 'originpos', 'originang'

2021-07-23 06:53 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +	local origin, offsetang = Vector(), Angle()
Done `local originpos, originang, headpos, headang`

2021-07-23 06:53 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +	local origin, oangle, headpos, headang
Done.

2021-07-24 23:07 UTC, merged

2022-08-13 11:23 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> -		trace.HitPos.Z = trace.HitPos.Z + math.Clamp(AdvDupe2.HeadZPos + GetConVarNumber("advdupe2_offset_z") or 0, -16000, 16000)
This will make your dupe go up or down when you pause the game.

2022-08-13 11:25 UTC, dvdvideo1234 commented on lua/advdupe2/cl_ghost.lua
> +		originpos = Vector(trace.HitPos); originpos.z = originpos.z + pz
The above problem is fixed here by crating a copy of the vector.