Replace all usermessages with net.
wiremod/advdupe2 pull request #385
Opened 2022-01-19 11:16 UTC by Aspect12

Hi.

I have replaced all usermessages with net due to a recent exploit that a server I'm developing for has been getting hammered with. Not to mention umsg is deprecated, so this does no harm.

I've tested the addon in singleplayer and everything seems to be working fine, though feel free to bugtest too if you wish.

2022-01-19 20:21 UTC, thegrb93 requested changes

2022-01-19 20:21 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +				net.Start("AdvDupe2_RemoveGhosts")
This is SERVER code so we should be sending to the client

2022-01-19 20:21 UTC, thegrb93 commented on lua/autorun/server/advdupe2_sv_init.lua
> +		net.WriteFloat(typ or 0)
WriteUInt(8, typ or 0) instead of WriteFloat

2022-01-19 20:21 UTC, thegrb93 commented on lua/autorun/client/advdupe2_cl_init.lua
> +	AdvDupe2.Notify(net.ReadString(), net.ReadFloat(), net.ReadFloat())
ReadUInt(8) instead of ReadFloat

2022-01-19 22:17 UTC, Divran commented on lua/autorun/server/advdupe2_sv_init.lua
> +		net.WriteFloat(typ or 0)
it's value first, number of bits second https://wiki.facepunch.com/gmod/net.WriteUInt

2022-01-19 22:58 UTC, Aspect12 reviewed
Done - apologies for the SendToServer thing, not sure how that slipped up.

2022-01-19 23:33 UTC, thegrb93 requested changes

2022-01-19 23:33 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +					net.WriteFloat(0)
These two should be net.WriteUInt(x, 16), and the corresponding ReadFloats should be updated too.

2022-01-19 23:33 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> -	function AdvDupe2.UpdateProgressBar(ply, perc)
Isn't this function needed?

2022-01-20 21:21 UTC, thegrb93 commented
@Aspect12

2022-01-20 22:50 UTC, Aspect12 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> -	function AdvDupe2.UpdateProgressBar(ply, perc)
It was a duplicate. It exists right above.

2022-01-22 09:55 UTC, thegrb93 approved these changes

2022-02-02 20:36 UTC, merged