Style
wiremod/advdupe2 pull request #417
Opened 2023-04-12 20:47 UTC by wrefgtzweve

2023-04-12 21:21 UTC, thegrb93 requested changes

2023-04-12 21:21 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +			end
Move down to line 1064

2023-04-12 21:21 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +
Some factory functions create multiple entities so we may need this to be a list entities and have a table.Empty call before each factory call. This hook should also only be created when we start pasting and removed when we stop pasting (you'll need to suffix the hook name with the player index and change lastEnt to Player.AdvDupe2.lastEntList or something).

2023-04-12 21:58 UTC, wrefgtzweve commented on lua/advdupe2/sv_clipboard.lua
> +
It'd be near impossible to figure out which entities we created by the function if it's not done in a single tick (unless im missing something) so i came with the idea to add the hook before the call and remove it after it to catch all created ents in that specific call.

2023-04-14 04:44 UTC, thegrb93 requested changes

2023-04-14 04:44 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +			print("Advanced Duplicator 2: Error creating entity, removing last created entities", lastEnt)
lastEnt here doesn't exist anymore.

2023-04-14 04:44 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +			if not status then ErrorNoHaltWithStack(valid) end
This line could be moved where the remove code is.

2023-04-18 17:54 UTC, thegrb93 commented
I just need to take a second to test it tonight

2023-04-18 23:52 UTC, merged