Master
wiremod/advdupe2 pull request #437
Opened 2023-08-23 16:34 UTC by wrefgtzweve

2023-08-25 16:49 UTC, thegrb93 requested changes

2023-08-25 16:49 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +                end
Use tabs instead of spaces here

2023-08-25 16:49 UTC, thegrb93 commented on lua/autorun/server/advdupe2_sv_init.lua
> +CreateConVar("AdvDupe2_DebugInfo", "0", {FCVAR_ARCHIVE}, "Should extra info be printed to console?", 0, 1)
Can you move this down to where the other convars are defined (Line 47)?

2023-08-25 21:56 UTC, wrefgtzweve commented on lua/autorun/server/advdupe2_sv_init.lua
> +CreateConVar("AdvDupe2_DebugInfo", "0", {FCVAR_ARCHIVE}, "Should extra info be printed to console?", 0, 1)
No because the files are included before it

2023-08-26 20:43 UTC, brandonsturgeon commented
This is a good change.

I was curious, so I took some metrics.

On CFC's Build/Kill server, since `Jan 17th, 2021`, these log lines _(not including the newlines that used to be printed with them)_ totaled: **4.7 gigabytes** across **60,103,081** total lines. 

119 days saw more than **100,000** of these lines printed, and 5 days saw more than **500,000**.

Pretty nuts.

2023-08-26 20:50 UTC, merged