Changed: Localize `ply.AdvDupe2` as  `dupe = ply.AdvDupe2`
wiremod/advdupe2 pull request #450
Opened 2024-01-05 09:36 UTC by dvdvideo1234

Reduced: Length of some long identifier lines

2024-01-05 21:37 UTC, thegrb93 requested changes

2024-01-05 21:37 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +		if(not dupe.Entities) then return false end
This can be `if not (dupe and dupe.Entities) then` and remove the check on line 207

2024-01-05 21:37 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +			AdvDupe2.Notify(ply,"Advanced Duplicator 2 in hold.", NOTIFY_ERROR)
What does 'in hold' mean?

2024-01-05 21:37 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +		if(not ply.AdvDupe2) then
Move `local dupe = ply.AdvDupe2` above this and change to `if not dupe then`

2024-01-05 21:37 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +		local dupe = ply.AdvDupe2
```lua
local dupe = ply.AdvDupe2
if not dupe then dupe = {} ply.AdvDupe2 = dupe end
```

2024-01-05 21:37 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +		local dupe = ply.AdvDupe2
```lua
local dupe = ply.AdvDupe2
if not dupe then dupe = {} ply.AdvDupe2 = dupe end
```

2024-01-06 14:58 UTC, dvdvideo1234 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +			AdvDupe2.Notify(ply,"Advanced Duplicator 2 in hold.", NOTIFY_ERROR)
Process is put on hold ( postponed )until thre is `AdvDupe2` available

2024-01-06 15:03 UTC, dvdvideo1234 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +		if(not dupe.Entities) then return false end
Fixed in: https://github.com/wiremod/advdupe2/pull/450/commits/1fb2640707f6b41b9cd6afd5b626b6299dbe0615

2024-01-06 15:03 UTC, dvdvideo1234 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +		if(not ply.AdvDupe2) then
Fixed in: https://github.com/wiremod/advdupe2/pull/450/commits/1fb2640707f6b41b9cd6afd5b626b6299dbe0615

2024-01-06 15:03 UTC, dvdvideo1234 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +		local dupe = ply.AdvDupe2
Fixed in: https://github.com/wiremod/advdupe2/pull/450/commits/1fb2640707f6b41b9cd6afd5b626b6299dbe0615

2024-01-06 15:03 UTC, dvdvideo1234 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +		local dupe = ply.AdvDupe2
Fixed in: https://github.com/wiremod/advdupe2/pull/450/commits/1fb2640707f6b41b9cd6afd5b626b6299dbe0615

2024-01-06 20:02 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +			AdvDupe2.Notify(ply,"Advanced Duplicator 2 in hold.", NOTIFY_ERROR)
Just create the table and continue. I don't think there's a reason to stop.

2024-01-06 20:05 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +			if(dupe.Downloading)then
Need `local dupe = ply.AdvDupe2` in this function

2024-01-08 07:04 UTC, dvdvideo1234 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +			if(dupe.Downloading)then
Fixed in: https://github.com/dvdvideo1234/advdupe2/commit/5024b68691f864c7c6c69602cf864fb18d989498

2024-01-08 07:04 UTC, dvdvideo1234 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
> +			AdvDupe2.Notify(ply,"Advanced Duplicator 2 in hold.", NOTIFY_ERROR)
Fixed in: https://github.com/dvdvideo1234/advdupe2/commit/5024b68691f864c7c6c69602cf864fb18d989498

2024-01-08 18:13 UTC, thegrb93 approved these changes

2024-01-08 18:14 UTC, merged