Fixed a crash exploit
wiremod/advdupe2 pull request #462
Opened 2024-03-26 07:23 UTC by NotAPorcupine

Spawning props with model scale set to 0 crashes dedicated servers. By adding this line of code, the MakeProp function will skip anything with ModelScale set to 0. Developers can modify this part of the code to detect people attempting to crash their server.

2024-03-26 07:28 UTC, thegrb93 commented
Can you report to garrysmod-issues as well?

2024-03-26 07:29 UTC, thegrb93 commented
Clamping the scale, 1e-5 to 1e5, would be better than just checking if its 0.

2024-03-26 07:30 UTC, NotAPorcupine commented
> Can you report to garrysmod-issues as well?

Where to do this?

2024-03-26 07:35 UTC, thegrb93 commented
> > Can you report to garrysmod-issues as well?
> 
> Where to do this?

https://github.com/Facepunch/garrysmod-issues

2024-03-27 21:23 UTC, thegrb93 requested changes

2024-03-27 21:23 UTC, thegrb93 commented on lua/advdupe2/sv_clipboard.lua
> +    if Data.ModelScale and Data.ModelScale == 0 then return end // Crashes dedicated servers when model scale is set to 0 in dupes. Skip the prop.
```suggestion
    if Data.ModelScale then Data.ModelScale = math.Clamp(Data.ModelScale, 1e-5, 1e5) end
```

2024-03-28 19:18 UTC, thegrb93 approved these changes

2024-03-28 19:18 UTC, merged