Add adjustable ghost rate
wiremod/advdupe2 pull request #493
Opened 2024-12-29 09:11 UTC by brandonsturgeon

### Description
Clientside ghosting can be slow. It's capped at generating one entity per `Tick`.

I feel like this is an outdated limit. Spawning them orders of magnitude more often doesn't seem to have any performance impact.

### Solution
I added a new convar + slider that adjusts how many ghosts are spawned per tick.

### Demo

https://github.com/user-attachments/assets/3371242a-f5ff-42fc-a515-b2b508482471

2024-12-30 09:10 UTC, thegrb93 requested changes

2024-12-30 09:10 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	local BusyBar           = AdvDupe2.BusyBar
Don't do this, it just makes the code very messy. The rest of the changes look good

2024-12-30 12:29 UTC, brandonsturgeon commented on lua/advdupe2/cl_ghost.lua
> +	local BusyBar           = AdvDupe2.BusyBar
formatter must've done it, i'll change it

2024-12-30 22:12 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	local BusyBar           = AdvDupe2.BusyBar
I mean the localization of those variables

2024-12-31 01:53 UTC, brandonsturgeon commented on lua/advdupe2/cl_ghost.lua
> +	local BusyBar           = AdvDupe2.BusyBar
Alright I'll change it back - I think it makes the code worse and hard to read. (also there's just no reason to be indexing tables this much 🤷) 

https://github.com/wiremod/advdupe2/pull/493/commits/051c40ebf31d862a6bd75edda743589df914fa8b

2024-12-31 09:49 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	local BusyBar           = AdvDupe2.BusyBar
Well, it would've been best if a ghost spawner class was made and used instead of doing it all on the global AdvDupe2 table, but this is fine.

2024-12-31 09:49 UTC, thegrb93 approved these changes

2024-12-31 16:15 UTC, thegrb93 requested changes

2024-12-31 16:15 UTC, thegrb93 commented on lua/weapons/gmod_tool/stools/advdupe2.lua
>  	CreateClientConVar("advdupe2_limit_ghost", 100, false, true)
Can limit_ghost be clamped 0 to 100?

2024-12-31 16:15 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	if currentGhost > maxGhosts then StopGhosting() return end
```lua
	local finalGhost = math.min( AdvDupe2.TotalGhosts, math.max( math.Round( (ghostPercentLimit / 100) * AdvDupe2.TotalGhosts ), 0 ) )
	local finalGhostInFrame = math.min( AdvDupe2.CurrentGhost + ghostsPerTick - 1, finalGhost )

	for i = AdvDupe2.CurrentGhost, finalGhostInFrame do
		local g = AdvDupe2.GhostToSpawn[i]
		if g then AdvDupe2.GhostEntities[currentGhost] = MakeGhostsFromTable( g ) end
	end
	AdvDupe2.CurrentGhost = finalGhostInFrame + 1

	AdvDupe2.UpdateGhosts( true )
	if not AdvDupe2.BusyBar then
		AdvDupe2.ProgressBar.Percent = (currentGhost / AdvDupe2.TotalGhosts) * 100
	end

	if AdvDupe2.CurrentGhost > finalGhost then
		StopGhosting()
	end
```

2024-12-31 16:17 UTC, thegrb93 commented
The `if AdvDupe2.CurrentGhost == AdvDupe2.HeadEnt then AdvDupe2.CurrentGhost = AdvDupe2.CurrentGhost + 1 end` might need to be moved inside the loop. Not sure yet how that behaves.

2024-12-31 16:19 UTC, thegrb93 commented
Maybe just need to do
`if i~=AdvDupe2.HeadEnt and g~=nil then AdvDupe2.GhostEntities[currentGhost] = MakeGhostsFromTable( g ) end`

2024-12-31 20:20 UTC, brandonsturgeon commented on lua/advdupe2/cl_ghost.lua
> +	if currentGhost > maxGhosts then StopGhosting() return end
Could you highlight the section you'd like rewritten and use the suggestion feature? I'll just apply it there

2025-01-01 02:38 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +	if currentGhost > maxGhosts then StopGhosting() return end
It doesn't allow suggestion feature there. This replaces the whole block

2025-01-03 01:58 UTC, brandonsturgeon commented on lua/advdupe2/cl_ghost.lua
> +	if currentGhost > maxGhosts then StopGhosting() return end
Applied, tested ✔️

2025-01-03 03:32 UTC, thegrb93 requested changes

2025-01-03 03:32 UTC, thegrb93 commented on lua/advdupe2/cl_ghost.lua
> +		if g then AdvDupe2.GhostEntities[i] = MakeGhostsFromTable( g ) end
```suggestion
		if g and i~=AdvDupe2.HeadEnt then AdvDupe2.GhostEntities[i] = MakeGhostsFromTable( g ) end
```

2025-01-03 05:28 UTC, brandonsturgeon commented on lua/advdupe2/cl_ghost.lua
> +		if g then AdvDupe2.GhostEntities[i] = MakeGhostsFromTable( g ) end
✔️

2025-01-03 05:58 UTC, thegrb93 approved these changes

2025-01-03 05:59 UTC, merged